"""readded MutableLists

Revision ID: b79e57eb113c
Revises: b9e3ebf83d5d
Create Date: 2024-07-05 13:05:26.933404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79e57eb113c'
down_revision = 'b9e3ebf83d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ent_names', sa.PickleType(), nullable=True))

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_history', sa.PickleType(), nullable=True))

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ent_names', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('ent_names')

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('stage_history')

    with op.batch_alter_table('art', schema=None) as batch_op:
        batch_op.drop_column('ent_names')

    # ### end Alembic commands ###
