"""initial Entity creation

Revision ID: bb60cf90e494
Revises: 
Create Date: 2024-06-17 00:20:20.927272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb60cf90e494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('stage_current', sa.Integer(), nullable=False),
    sa.Column('stage_EM4view', sa.Integer(), nullable=False),
    sa.Column('date_started', sa.String(length=10), nullable=False),
    sa.Column('date_ended', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('corp_fam', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity')
    # ### end Alembic commands ###
