"""add data_map to store DOT syntax mini graph db

Revision ID: 1496c69a1f16
Revises: f8241e56cbdd
Create Date: 2025-01-05 20:44:08.842756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1496c69a1f16'
down_revision = 'f8241e56cbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_map', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('data_map')

    # ### end Alembic commands ###
