"""add News.judgment and stg no.

Revision ID: 1fc7fcd5abc5
Revises: 3d812cda43db
Create Date: 2024-10-18 19:47:13.373532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc7fcd5abc5'
down_revision = '3d812cda43db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judgment', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('stage_int_value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('stage_int_value')
        batch_op.drop_column('judgment')

    # ### end Alembic commands ###
