"""user validation and access

Revision ID: 27c6d8ee0cf4
Revises: 476368a9edcb
Create Date: 2024-09-16 17:50:04.121481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c6d8ee0cf4'
down_revision = '476368a9edcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validations', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_access', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_access')
        batch_op.drop_column('validations')

    # ### end Alembic commands ###
