"""added SurveyNewUser

Revision ID: 3d812cda43db
Revises: 27c6d8ee0cf4
Create Date: 2024-09-27 20:42:58.241922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d812cda43db'
down_revision = '27c6d8ee0cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_new_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discovery', sa.Text(), nullable=True),
    sa.Column('thoughts', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('monetization', sa.Text(), nullable=True),
    sa.Column('datetime', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_new_user')
    # ### end Alembic commands ###
