"""add class User

Revision ID: 476368a9edcb
Revises: b79e57eb113c
Create Date: 2024-09-13 21:41:45.406738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476368a9edcb'
down_revision = 'b79e57eb113c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('func_stage', sa.Integer(), nullable=False),
    sa.Column('per_page', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.String(length=16), nullable=False),
    sa.Column('ranking_sort', sa.String(length=10), nullable=False),
    sa.Column('ranking_cats', sa.String(length=16), nullable=False),
    sa.Column('ranking_stat', sa.String(length=10), nullable=False),
    sa.Column('viewing_mode', sa.String(length=10), nullable=False),
    sa.Column('to_view', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
