"""alert notifications

Revision ID: f47f398aface
Revises: 1496c69a1f16
Create Date: 2025-01-23 23:32:33.734187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47f398aface'
down_revision = '1496c69a1f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notification_frequency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('alert_on_art_item', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alert_on_reference_item', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('categories_following', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('entities_following', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('alert_on_stage_change', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alert_on_news_item', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_suggestions', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_suggestions')
        batch_op.drop_column('alert_on_news_item')
        batch_op.drop_column('alert_on_stage_change')
        batch_op.drop_column('entities_following')
        batch_op.drop_column('categories_following')
        batch_op.drop_column('alert_on_reference_item')
        batch_op.drop_column('alert_on_art_item')
        batch_op.drop_column('notification_frequency')
        batch_op.drop_column('last_sent')
        batch_op.drop_column('enable_notifications')

    # ### end Alembic commands ###
